[package]
edition = "2018"
name = "wasm-lsp"
version = "0.0.0"
authors = ["hvithrafn <hvithrafn@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
description = """
A language server implementation for WebAssembly.
"""

[dependencies]
